version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres-test-volume:/var/lib/postgres/data
      - postgres-config:/etc/postgres

  app-docker:
    build:
      context: .
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 2500:3000
    depends_on:
      - postgresdb

volumes:
  postgres-test-volume:
  postgres-config:
